version: 2                                                                                                                      
sources:                                                                                                                        
  - name: bronze_check                                                                                                          
    description: "Verify values inside of the bronze0 table are correct."
    catalog: warehouse                      
    schema: bronze                      
    tables:
      - name: bronze0                                                                                                           
        columns:
          - name: ItemHash                                                                                                      
            data_tests:
              - not_null                    
              - unique 